import data from "../fixtures/rediff.json"
describe('Rediffregister', () => {
    it('Demo test for register', () => {
      cy.visit(data.url)
      cy.get('#tblcrtac > tbody > tr:nth-child(3) > td:nth-child(3) > input[type=text]').type(data.fullname)
     
      cy.get('#tblcrtac > tbody > tr:nth-child(7) > td:nth-child(3) > input[type=text]:nth-child(1)').type(data.rediffmailid)
      cy.get('input[id="newpasswd"]').type(data.password)
      cy.get('input[id="newpasswd1"]').type(data.password)
      //cy.get('#div_altemail > table > tbody > tr:nth-child(1) > td:nth-child(3) > input[type=text]').type('arpitha@gmail.com')
      cy.get('input[onclick="chk_altemailID();fieldTrack(this);"]').check()
      //cy.get('#div_hintQS > table > tbody > tr:nth-child(2) > td:nth-child(3) > select').type("Select from the list")
      //cy.contains('What is the name of your first school?').click({force: true})
      //cy.get('select[onchange="fieldTrack(this);"]').select("What is the name of your first school?")
      cy.get('#div_hintQS > table > tbody > tr:nth-child(2) > td:nth-child(3) > select').select(data["security question"])
      cy.get('#div_hintQS > table > tbody > tr:nth-child(4) > td:nth-child(3) > input[type=password]').type(data.Answer)
      cy.get('#div_hintQS > table > tbody > tr:nth-child(6) > td:nth-child(3) > input[type=text]').type(data.Maidenname)
      //cy.get("#div_mob > table > tbody > tr > td:nth-child(3) > div:nth-child(2)").type('+91')
      //cy.get("#country_id > ul").click({force :true})
      //cy.get("#country_id > ul").type('+91')
      //cy.get('div[id="country_id"]').type('India (+91)')
      cy.contains(data.Countrycode).click({force: true})
      cy.get('input[id="mobno"]').type(data.mobno)
      cy.get('#tblcrtac > tbody > tr:nth-child(23) > td:nth-child(3) > select:nth-child(1)').select(data.day)
      cy.get('#tblcrtac > tbody > tr:nth-child(23) > td:nth-child(3) > select:nth-child(2)').select(data.month)
      cy.get('#tblcrtac > tbody > tr:nth-child(23) > td:nth-child(3) > select:nth-child(3)').select(data.year)
      cy.get('input[value="f"]').check()
      cy.get('select[id="country"]').select(data.country)
      //cy.contains('Agartala').click({force: true})
      cy.get('select[onchange="showothcity();fieldTrack(this);"]').select(data.city)
    })
  })